Feature enqueue target brands
Trenbe/infinity-product pull request #4
Opened 2021-07-09 09:02 UTC by neosuram

- Subnet 적용
- iamroll -> 개별 lambda function에 지정 (plugin: serverless-iam-roles-per-function 추가)
- env.isDev체크하여 Dev에서 실제 큐에 작업하지 않도록 예외 처리
- enqueueTargetBrand count parameter pathParameter로 변경

2021-07-12 02:28 UTC, zestime requested changes

2021-07-12 02:28 UTC, zestime commented on functions/src/API/enqueue-target-brands/handler.ts
> +                CommonQueueCount: results.filter(b=>!b.useChrome).length,
별거 아니지만, reduce로 한 번에 counting 하는게 좋았을 것 같습니다.
filter가 5번 도는건 관리도 편해 보이지 않네요.

2021-07-12 02:28 UTC, zestime commented on functions/src/API/enqueue-target-brands/handler.ts
> +    console.log('update : ' + brand.name + '(' + brand.id + ') - ' + brand.isBrowserLinkParser);
Template literal로 변경하는게 더 좋아 보입니다.

2021-07-12 02:28 UTC, zestime commented on functions/src/API/enqueue-target-brands/handler.ts
> +      result = { brandName, brandId, useChrome, success: true };
result와 send 메서드 사이에 관련성을 찾기 어렵습니다.
return에서 define하는 것은 어떨까요?
catch에서는 error만 assign하면 더 깔끔할 것 같습니다.

2021-07-12 02:28 UTC, zestime commented on functions/src/functions/run-enqueue-target-brands/handler.ts
> +    result = await lambda.invoke(params).promise();
코드 내용상, 여기서 return하는게 더 명확할 것 같습니다.

2021-07-12 07:05 UTC, neosuram commented on functions/src/API/enqueue-target-brands/handler.ts
> +                CommonQueueCount: results.filter(b=>!b.useChrome).length,
한번에 카운팅 한 후 값을 넣도록 변경했습니다.

2021-07-12 07:05 UTC, neosuram commented on functions/src/API/enqueue-target-brands/handler.ts
> +    console.log('update : ' + brand.name + '(' + brand.id + ') - ' + brand.isBrowserLinkParser);
관련하여 전체적으로 Template literal 로 변경했습니다.

2021-07-12 07:06 UTC, neosuram commented on functions/src/API/enqueue-target-brands/handler.ts
> +      result = { brandName, brandId, useChrome, success: true };
실행결과 성공여부 및 에러만 가져오고 나머지는 리턴시에 기존 변수들을 활용하도록 변경했습니다.

2021-07-12 07:07 UTC, neosuram commented on functions/src/functions/run-enqueue-target-brands/handler.ts
> +    result = await lambda.invoke(params).promise();
try , catch 별도 결과 리턴되도록 변경했습니다.

2021-07-13 01:18 UTC, zestime approved these changes

2021-07-13 07:37 UTC, merged